lgm_doctorant:
    resource: "@LgmBundle/Controller/DoctorantController.php"
    type:     annotation

lgm:
    resource: "@LgmBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"